# This file will lint the specified files/directories.
# Workflow adapted from https://github.com/r-lib/actions/tree/v2/examples

on:
  push:
    branches: [main]
  workflow_dispatch:

name: lint

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::lintr, any::cyclocomp, local::.
          needs: lint

      - name: Lint package
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true

      - name: Lint rmarkdown
        run: lintr::lint_dir("rmarkdown")
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
